In [1]:
import numpy as np

1.  Create two arrays from array a, one with 4/5 and the other with 1/5 of the elements that doesn't mess up the original array a.

In [2]:
a = np.random.normal(0,1,1000)

#Your code below
a1=a[:800]
a2=a[800:]
len(a1),len(a2)

(800, 200)

2. Print out every 50th element on the last 400 elements of a and store it in an element called "g".

In [3]:
g = []
print(len(a[-400:]))
for index,value in enumerate(a[-400:]):
    if (index+1)%50==0:
        print(value)
        g.append(value)
g   

400
0.5895929372091583
-1.18362442595465
0.26043331011741844
-0.06904585315072503
-0.5588474176270439
-0.1006062439773497
-1.0467492139875587
-1.5523190632488753


[0.5895929372091583,
 -1.18362442595465,
 0.26043331011741844,
 -0.06904585315072503,
 -0.5588474176270439,
 -0.1006062439773497,
 -1.0467492139875587,
 -1.5523190632488753]

3. Create an array of your top 5 favorite foods in an array called food.

In [4]:
food = np.array(['food1','food2','food3','food4','food5'])
food

array(['food1', 'food2', 'food3', 'food4', 'food5'], dtype='<U5')

4. Multiply every element in the array "g" by 10. Then try multiplying every element in the array "food" by 10 as well... does this error out? If so, why?

In [7]:
g = np.array(g)
print(g*10)
print(food*10)

[  5.89592937 -11.83624426   2.6043331   -0.69045853  -5.58847418
  -1.00606244 -10.46749214 -15.52319063]


TypeError: ufunc 'multiply' did not contain a loop with signature matching types dtype('<U5') dtype('<U5') dtype('<U5')

5. Create a 6 x 4 matrix filled with random numbers (created via numpy's random function).

In [13]:
matrix=np.random.rand(6,4)
matrix

array([[0.75701419, 0.28608305, 0.17046358, 0.76127483],
       [0.40071057, 0.3123936 , 0.60941704, 0.68553676],
       [0.67126665, 0.07421085, 0.04379949, 0.74686975],
       [0.46006334, 0.87224115, 0.16149625, 0.33605915],
       [0.65422163, 0.73284359, 0.02680465, 0.61913514],
       [0.01475495, 0.27149681, 0.08459975, 0.65601923]])

6. Transpose the matrix you created above and print out its size, dimensions and shape.

In [16]:
matrix.T.size,matrix.T.ndim,matrix.T.shape

(24, 2, (4, 6))

7. Print out the maximum of the 2nd row and the sum of the 3rd column.

In [19]:
print ('2nd Row sum:',matrix.T.sum(axis=1)[1])
print ('3rd Column sum:',matrix.T.max(axis=0)[2])

2nd Row sum: 2.54926905362626
3rd Column sum: 0.7468697549801805


8. Create an identity of matrix that has 3 rows and 3 columns. Then print out the identity matrix multiplied by "g". Also print out the matrix "g" multiplied by itself ("g") as well.

In [20]:
g = np.array([[1,2,3],[4,5,6],[7,8,9]])

#Your code below
eye = np.eye(3,3)
print(np.dot(eye,g))
print(np.dot(g,g))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
